### ISSUE TITLE
Build on OS X

### ISSUE THREAD

**Issue by jamesstout** [hroptatyr/dateutils#11]
Hi,  should this build on OS X (10.8.3) 

I'm getting errors with the default `gcc` version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

So I installed `gcc-4.8`. I still get errors. Initially the `autoreconf -i` command puts a random `.` on line 4 of `configure` which kills the command. Removing that and using gcc 4.8, I get errors.

The log shows:

```
conftest.c:4:25: warning: missing terminating " character [enabled by default]
 #define PACKAGE_VERSION "-n
                         ^
conftest.c:5:1: warning: missing terminating " character [enabled by default]
 "
 ^
conftest.c:5:1: error: missing terminating " character
conftest.c:6:24: warning: missing terminating " character [enabled by default]
 #define PACKAGE_STRING "dateutils -n
                        ^
conftest.c:7:1: warning: missing terminating " character [enabled by default]
 "
 ^
conftest.c:7:1: error: missing terminating " character
conftest.c:11:17: warning: missing terminating " character [enabled by default]
 #define VERSION "-n
                 ^
conftest.c:12:1: warning: missing terminating " character [enabled by default]
 "
 ^
conftest.c:12:1: error: missing terminating " character
configure:3273: $? = 1
configure:3311: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "dateutils"
| #define PACKAGE_TARNAME "dateutils"
| #define PACKAGE_VERSION "-n
| "
| #define PACKAGE_STRING "dateutils -n
| "
| #define PACKAGE_BUGREPORT "https://github.com/hroptatyr/dateutils"
| #define PACKAGE_URL ""
| #define PACKAGE "dateutils"
| #define VERSION "-n
| "
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
```

See the closing `"` are on newlines?

If I re-write as:

``` cpp
/* confdefs.h */
#define PACKAGE_NAME "dateutils"
#define PACKAGE_TARNAME "dateutils"
#define PACKAGE_VERSION "-n"
#define PACKAGE_STRING "dateutils -n"
#define PACKAGE_BUGREPORT "https://github.com/hroptatyr/dateutils"
#define PACKAGE_URL ""
#define PACKAGE "dateutils"
#define VERSION "-n"
/* end confdefs.h.  */

int
main ()
{

  ;
  return 0;
}
```

It compiles fine with `gcc confdefs.c`

Any ideas?
